name: Deploy to Fly.io

on:
  push:
    branches: [main]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install flyctl
        run: |
          curl -L https://fly.io/install.sh  | sh
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Login to Fly.io
        run: flyctl auth login --token $FLY_API_TOKEN

      - name: Deploy app
        run: |
          flyctl launch --no-organization --name shadowsocks-app --region fra --port 8321 --yes
          flyctl deploy
